spring:
  application:
    name: Uni_ERP

  datasource:
    url: jdbc:mysql://localhost:3306/uni_ERP?useSSL=false&serverTimeZone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asd123

  profiles:
    active: dev, db  # prod  # ?? ??? ????? dev? ??
