spring:
  sql:
    init:
      mode: always  # (optional) 스키마 및 데이터 초기화 활성화
      data-locations:
        - classpath:db/data.sql
        - classpath:db/notice.sql
        - classpath:db/product.sql
        - classpath:db/hr.sql
        - classpath:db/salesData.sql
        - classpath:db/data/*
        - classpath:db/salesData2.sql
        - classpath:db/salesData3.sql
        - classpath:db/salesData4.sql
        - classpath:db/salesData5.sql
        - classpath:db/salesData6.sql
