server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/ # JSP 파일이 위치한 디렉토리 접두사를 설정합니다.
      suffix: .jsp
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:uni_ERP;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10 # 한 번에 들고오는 개수 설정
    defer-datasource-initialization: true

  output:
    ansi:
      enabled: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: dev1email1smtp@gmail.com
    password: durn wzqw ghqg zetk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

logging:
  level:
    '[com.uni.uni_erp]': DEBUG

coolsms:
  api:
    key: "NCS9GARPFNB2EJXK"
    secret: "DBM9X06ZF3VXI8AHHPDWQOGVYQPOBZE9"
    number: "010-6439-5737"